### ISSUE TITLE
Only Partial TV support

### ISSUE THREAD

**Issue by Net-time** [icapurro/smartdns#1]
Hi!
Does not work with a tv-remote (D-Pad support).
Works fine if I use a mouse.
Tried to import and sync the project, but get too many errors for my limited knowledge.
Any chance of getting D-Pad function?

**Comment by lostgit** [comment]
It works. On TV, the app starts with the focus off-screen. To get the focus on the screen, click DOWN then UP on the remote. 

The Start button on the screen now has the focus (though not very obvious with the dark background).

**Comment by Net-time** [comment]
True, and thanks :)
